[2021-08-10 15:45:40,002] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-08-05T09:00:00+00:00 [queued]>
[2021-08-10 15:45:40,009] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2021-08-05T09:00:00+00:00 [queued]>
[2021-08-10 15:45:40,009] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-08-10 15:45:40,010] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-08-10 15:45:40,010] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-08-10 15:45:40,023] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2021-08-05T09:00:00+00:00
[2021-08-10 15:45:40,026] {standard_task_runner.py:54} INFO - Started process 12309 to run task
[2021-08-10 15:45:40,198] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_aluraonline', '2021-08-05T09:00:00+00:00', '--job_id', '15', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/tmp/tmp_9fftu98']
[2021-08-10 15:45:40,198] {standard_task_runner.py:78} INFO - Job 15: Subtask twitter_aluraonline
[2021-08-10 15:45:40,227] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2021-08-05T09:00:00+00:00 [running]> on host SAFIRA-097.safira.local
[2021-08-10 15:45:40,246] {taskinstance.py:1150} ERROR - unexpected '%'
Traceback (most recent call last):
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 965, in _run_raw_task
    self.render_templates(context=context)
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1424, in render_templates
    self.task.render_template_fields(context)
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 719, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 726, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 755, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ibernardes/datapipeline/.env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
[2021-08-10 15:45:40,250] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20210805T090000, start_date=20210810T184540, end_date=20210810T184540
[2021-08-10 15:45:44,990] {local_task_job.py:102} INFO - Task exited with return code 1
